# Generated by Django 4.2.6 on 2023-10-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Levels_pyramid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('gender', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=50)),
                ('dynasty', models.CharField(max_length=80)),
                ('tall', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('joke_names', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('organizations', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=30)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=150)),
                ('read_task', models.TextField(default='|0', null=True)),
                ('check_task', models.BooleanField(default=False)),
                ('id_task', models.IntegerField(default=0)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Imperial_BD.levels')),
                ('level_pyramid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Imperial_BD.levels_pyramid')),
            ],
        ),
    ]
