# Generated by Django 4.2.6 on 2023-10-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imperial_BD', '0002_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Universe',
                'verbose_name_plural': 'Universes',
            },
        ),
    ]
