# Generated by Django 4.2.6 on 2023-10-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imperial_BD', '0003_universes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='universe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Imperial_BD.universes'),
        ),
    ]
